site_name: {{ cookiecutter.project_name }}
site_description: {{ cookiecutter.project_short_description }}

theme:
    name: 'material'
    logo: img/logo.svg
    features:
        - header.autohide
        - navigation.instant
        - navigation.tabs

repo_name: {{ cookiecutter.project_slug }}
# repo_url: https://dev.azure.com/technipfmc-dev/SubseaDesign/_git/fastpipe
edit_uri: ''

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tabbed

nav:
    - Home: index.md
    - Release Notes: release-notes.md
